import os, zipfile

# --- main.py (calculator app) ---
main_code = """from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput
from kivy.uix.button import Button

class Calculator(GridLayout):
    def __init__(self, **kwargs):
        super(Calculator, self).__init__(**kwargs)
        self.cols = 1
        self.result = TextInput(multiline=False, readonly=True, halign="right", font_size=55)
        self.add_widget(self.result)
        self.buttons = [
            ["7", "8", "9", "/"],
            ["4", "5", "6", "*"],
            ["1", "2", "3", "-"],
            ["C", "0", "=", "+"]
        ]
        grid = GridLayout(cols=4)
        for row in self.buttons:
            for label in row:
                grid.add_widget(Button(text=label, on_press=self.on_button_press, font_size=32))
        self.add_widget(grid)

    def on_button_press(self, instance):
        text = instance.text
        if text == "C":
            self.result.text = ""
        elif text == "=":
            try:
                self.result.text = str(eval(self.result.text))
            except Exception:
                self.result.text = "Error"
        else:
            self.result.text += text

class CalculatorApp(App):
    def build(self):
        return Calculator()

if __name__ == "__main__":
    CalculatorApp().run()
"""

# --- buildozer.spec ---
spec_code = """[app]
title = Calculator
package.name = calculator
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1
"""

# --- GitHub Action workflow ---
workflow_code = """name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: calculator-apk
          path: bin/*.apk
"""

# --- Create directories ---
os.makedirs(".github/workflows", exist_ok=True)

# Write files
with open("main.py", "w") as f: f.write(main_code)
with open("buildozer.spec", "w") as f: f.write(spec_code)
with open(".github/workflows/build.yml", "w") as f: f.write(workflow_code)

# Zip everything
zip_filename = "/content/calculator_github_template.zip"
with zipfile.ZipFile(zip_filename, "w") as zipf:
    zipf.write("main.py")
    zipf.write("buildozer.spec")
    zipf.write(".github/workflows/build.yml")

print("✅ Template ready:", zip_filename)
